### ISSUE TITLE
Create a template from string ?

### ISSUE THREAD

**Issue by remss** [thephpleague/plates#108]
Hello,
Is there a way to renderer a template from string instead of a file ?
In the case where the template is in a database or whatever.
Thanks.

**Comment by reinink** [comment]
Sorry, there is no way to do this at this time. In order to make this work there would have to be some type of `eval()` step, which makes me a bit nervous. I'd consider adding this functionality if I received more requests for it, but until this point this is the first time.

One solution is to simply save the string to a temporary file, and then render it. Of course this comes with some a performance hit.

**Comment by Remo** [comment]
Second time ;-)

I wouldn't mind the performance impact, but I've got a system where one can upload a master template as well as headers and footers in the UI and would thus have to write several files. Still considering it, but trying to avoid it..
