### ISSUE TITLE
problem about Template's layout / insert / fetch function

### ISSUE THREAD

**Issue by FreeEgg** [thephpleague/plates#116]
layout / insert / fetch function can not use parent's data
I change this code
$this->engine->render($name,  $data);
to
$this->engine->render($name, array_merge($this->data, $data));

**Comment by reinink** [comment]
Yeah this is intentional with Plates. Each template only has it's own variables. This is meant to prevent conflicts between variables, and generally works out pretty well.

There are some techniques to help with this. For example, [preassigned and shared data](http://platesphp.com/templates/data/#preassigned-and-shared-data) make it easy to assign data to a template each time it's rendered:

```php
$templates->addData(['name' => 'Jonathan'], ['login', 'template']);
```

If you're using layouts, you can [assign data](http://platesphp.com/templates/layouts/#assign-data) when you call the `layout` function:

```php
<?php $this->layout('template', ['title' => 'User Profile']) ?>
```

And in a similar way, if you're using nesting, you can [assign data](http://platesphp.com/templates/nesting/#assign-data) when you call the `insert` function:

```php
<?php $this->insert('partials/header', ['name' => 'Jonathan']) ?>
```

I hope that helps!
