### ISSUE TITLE
Class 'League\Plates\Template\Directory' not found

### ISSUE THREAD

**Issue by Skayo** [thephpleague/plates#127]
When im running my script I get this error:

> Fatal error: Class 'League\Plates\Template\Directory' not found in .../src/Engine.php on line 57

I installed it via the zip file from the releases page.

**PHP-Code**

``` php
<?php
// ...

// Include Plates (Template Engine)
include_once(".../src/Engine.php");

// Create new Plates instance
$templates = new League\Plates\Engine('themes/default/templates');

// ...
?>
```

The **...** is just a place holder for the full path. Didn't want to show it here

**Comment by DaGhostman** [comment]
I mightght be wrong here, but if you are not using composer or any other sort of autoloading you have to include every class that is needed.

I would strongly suggest that you invest some time in autoloading since it will ease you in the long run + make your code cleaner

**Comment by reinink** [comment]
Yes @DaGhostman is exactly right here. If you don't use Composer, you basically need to manually load all the classes included with this package, or even write your own auto-loader for it. Of course this isn't what I recommend. Using Composer is much simpler. 👍

**Comment by giro83** [comment]
I am currently trying Plates out, and I have run into this too.

I completely understand Composer may be the way to go, but think of people that have not used Composer -or- Plates before. If I am trying to learn Plates, I don't want to have to learn Composer first.

Given the installation page (http://platesphp.com/installation/) says you can just download the .ZIP file and use that, you may want to consider expanding on the instructions for that scenario.

I don't even have any clue what's in this auto-loader file, because it is not in your package and I imagine it's auto-generated by Composer. At least show what that looks like so we can mimic it in our scripts.

Just my two cents.

**Comment by giro83** [comment]
Requiring Engine.php and all of the PHP files in the Template directory did the trick for me (as in I was able to run the basic example on your website):

require 'plates/Engine.php';
require 'plates/Template/Directory.php';
require 'plates/Template/FileExtension.php';
require 'plates/Template/Folders.php';
require 'plates/Template/Functions.php';
require 'plates/Template/Data.php';
require 'plates/Template/Template.php';
require 'plates/Template/Name.php';
require 'plates/Template/Func.php';
require 'plates/Template/Folder.php';

Just logging this in case anyone else runs into this. I apologize if this is obvious stuff.

**Comment by Bibhas1999** [comment]
If you have downloaded or clone this project from github just run this command on terminal composer dump-autload it will generate the vendors folder along with autload files
