### ISSUE TITLE
Access an Extension from Another Extension

### ISSUE THREAD

**Issue by odahcam** [thephpleague/plates#152]
I'm creating a extension where I want to make use of the Assets Extension.

Is there a way to achieve this?

TA!

**Comment by tavy315** [comment]
Perhaps you can extend that extension?

**Comment by odahcam** [comment]
I would like to have all the available functions in the view, available inside my extension class.

I already finished my extension's first version, I simply copy 'n pasted the methods I needed.

**Comment by ragboyjr** [comment]
@odahcam Aren't you able to access your extension via the engine variable in your extension?

Or do you want to reuse helper methods from one extension to the other?

If helper methods, then you can use traits or any other OO design patterns to share code

**Comment by ragboyjr** [comment]
Any word @odahcam

**Comment by odahcam** [comment]
I'm little busy now, but I'll test something soon. I wanna use the Assets extension inside my own extension, now I've copy and pasted the Asset extension code into my extension and I really don't wanna this behavior.

**Comment by ragboyjr** [comment]
I've started on the 4.0 rewrite, this will not be a feature supported by plates. If you want to extend an extension, use decoration (preferred) or inheritance. But plates won't have any mechanisms supporting this except for maybe a doc reference.

**Comment by odahcam** [comment]
I don't wanna extend anything. I want to use an extension inside my extension to do some jobs using that other extension's features, like URL generation, for example: why should i have to write URL generation methods again for each new extension I will create? I Hope you understand what I'm trying to say here. BTW, I can extend anything just using some brain plus OOP logic, there's no reason for creating an issue for that. 😕 

Anyway, if you want to explain better what you'r saying with decorator pattern I would appreciate.

**Comment by ragboyjr** [comment]
@odahcam Few things

1. I won't be making any updates to the 3.x branch for this, so extensions will stay as is, If you want to reuse or augment the functionality of URI extension for example, you're only real choice is to extend or it just copy the code.
2. Now, for 4.x you likely will run into this issue as well because it just depends on how the extensions are written. If the extension class encapsulates the URI logic inside itself, then there's nothing you can do, but if it was written in a way that it uses URI helpers, then you could also utilize those helpers. I'll keep reusability in mind for the 4.x extensions for sure, but I'm not going to necessarily cater to allowing every method in an extension be re-usable.
