### ISSUE TITLE
Testcases to peridot

### ISSUE THREAD

**Issue by physcocode** [thephpleague/plates#174]
saw @ragboyjr comment on pull request  #157 , hence was tempted to try peridot I really liked it.
Assuming rewriting test cases is part of #166 I would like to volunteer in writing tests on peridot. @ragboyjr  how and where should I start with ? 

PS: I opened this issue to keep track of all pull request related to rewriting tests

**Comment by ragboyjr** [comment]
Well, v4 is a complete rewrite, not much is the same, but i'll stub out some tests for you so you can contribute, wouldn't mind the help :).

Once i get them stubbed, we can just call out in here which tests someone is working on so that we don't overlap. I was doing a good job doing TDD and testing as I develop, but i had to go through several iterations of design which made me want to test after i finished the design.

**Comment by ragboyjr** [comment]
@physcocode ok, i've made pending tests for everything. We are using [peridot/leo](http://peridot-php.github.io/leo/) for the assertion library and [eloquent/phony](http://eloquent-software.com/phony/latest/) for the mocking library.

**Comment by ragboyjr** [comment]
p.s. I just use `make test` to run the tests.
