### ISSUE TITLE
Plates as Templating Frontend?

### ISSUE THREAD

**Issue by ragboyjr** [thephpleague/plates#207]
One of the interesting side affects of the new V4 architecture is that Plates can support different renderers which could technically mean that plates could act as a frontend to a variety of templating languages like smarty/twig/blade. In V3, rendering was only done via including php files, in v4, we've moved this logic into the RenderTemplate interface which allows different implementations of Rendering Templates. In fact, as of v4, we currently support including non-php files via `file_get_contents` and also image files that are included are base64_encoded.

I'm not sure how useful it would be to use plates as a frontend for Blade or Twig, but maybe it could be helpful if you are migrating your templating system? not sure, but fun food for thought.

**Comment by carbontwelve** [comment]
I'm going to investigate this in Tapestry. Currently I have a number of [Renderers](https://www.tapestry.cloud/api/2.0.0-dev/Tapestry/Entities/Renderers.html) and it would be interesting to see if these could be implemented using V4.

**Comment by ragboyjr** [comment]
Let me know how that goes :) :thumbsup

**Comment by carbontwelve** [comment]
@lkraav I have been inundated with client work the past - well - eight months haha, so have yet to find any time to sit down with this.

**Comment by lkraav** [comment]
Yeah I know that feeling.

I'm currently enjoying the compatibility aspects of going PHP-only, so not worried about it too much.

**Comment by filips123** [comment]
I know that this issue is a bit old, but I have some idea about its topic. It may also not be related directly to Plates, but generally for PHP templates.

It would be good to have one universal way to use multiple templating frameworks. This could be done with creating some PSR standard for templating (which would be used by templating frameworks) and then creating some library which will be managing all templating frameworks (which would be used by the actual project).

So, you could create a project that would use some library to store all data/variables. Then you would be able to specify which templating framework to use and the library would correctly handle and use it. This would also enable you to use different themes which may use different templating frameworks and change templating framework with just changing the class name of the implementation.

This would enable you to use easily use multiple templating frameworks, such as Plates, Twig, Smarty, Mustache, or even some JS-based frameworks, like React, Vue and Angular.

**Comment by ragboyjr** [comment]
@filips123 I had a similar idea as well, but I just don't think it would be super practical. Also, the Symfony Templating component already is this pretty much.

I'm going to close this since I don't think this is the direction plates should go.
