### ISSUE TITLE
Can anyone please explain foreach and list?

### ISSUE THREAD

**Issue by nUKEmAN4** [thephpleague/plates#268]
So im looking at this example on https://platesphp.com/templates/syntax/ and i cant figure out how this works. Im new to php and things but i checked #144 #120 and some others but no luck. Can anyone please give better clarification?

This are my codes for test:

Template:
`                          <?php foreach($baz as $item): ?>
                            <div class="list-content">
                              <div class="list-content-item">
                                <h5><?=$this->e($item->foo)?></h5>
                              </div>
                            </div>
                          <?php endforeach ?>`

And:
```
$arr = array(array("foo" => "bar"), array("bar" => "foo"));

  $templates = new League\Plates\Engine($_SERVER['DOCUMENT_ROOT'].'/core/templates/Default');

  $template = $templates->make('planets/main_layout');
  $template->data([
    'baz' => $arr,
    'TEST_VAR' => 'yay'
  ]);

  echo $template;
```

**Comment by ragboyjr** [comment]
Hi @nUKEmAN4 welcome to PHP :). https://github.com/thephpleague/plates/discussions/269 This topic is much better suited for a discussion or stack overflow post and not for an issue since this isn't a bug report or feature request.

I'm going to close this for those reasons, but please feel free to open a discussion or stack overflow post around this question.
